name: Deploy to surge.sh

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 9
      - run: npm install -g surge && npm install
        name: Extract branch name
        shell: bash
      - run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: surge ./ nxs-${{ steps.extract_branch.outputs.branch }} --token ${{ secrets.SURGE_TOKEN }}
